require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'vodeoapp' do
  config = use_native_modules!

  use_react_native!
  pod 'JWPlayer-SDK', '~> 3.16.0'
  # pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'vodeoappTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

  post_install do |installer|
   
  end
end

target 'vodeoapp-tvOS' do
  # Pods for vodeoapp-tvOS

  target 'vodeoapp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
